package uz.app.bot.admin;

public enum AdminBotState {
    //for add categories
    ADD_CATEGORY_NAME,
    ADD_CATEGORY_DESCRIPTION,
    //for add products
    ADD_PRODUCT_CATEGORY,
    ADD_PRODUCT_NAME,
    ADD_PRODUCT_DESCRIPTION,
    ADD_PRODUCT_IMAGE,
    ADD_PRODUCT_PRICE,
    ADD_PRODUCT_QUANTITY_UNIT,
    ADD_PRODUCT_QUANTITY,
    CONFIRM_PRODUCT,
    //for manage categories and products
    MANAGE_CATEGORIES_AND_PRODUCTS,
    EDIT_CATEGORY,
    EDIT_CATEGORY_NAME,
    EDIT_CATEGORY_DESCRIPTION,
    DELETE_CATEGORY,
    EDIT_PRODUCT,
    EDIT_PRODUCT_NAME,
    EDIT_PRODUCT_DESCRIPTION,
    EDIT_PRODUCT_IMAGE,
    EDIT_PRODUCT_PRICE,
    EDIT_PRODUCT_QUANTITY_UNIT,
    EDIT_PRODUCT_QUANTITY,
    DELETE_PRODUCT,
}
